// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ojrhagsxqmhvvkquhrzt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9qcmhhZ3N4cW1odnZrcXVocnp0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxMzgwOTAsImV4cCI6MjA2OTcxNDA5MH0.2tBexUdiZbR5eFyqyGrjDPMD_Nqdw4nD4qz9tPxqMNE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});